name: Deploy to Elastic Beanstalk

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Install dependencies
      - name: Install Dependencies
        run: npm ci

      # Build the project
      - name: Build the project
        run: npm run build

      # Zip the build output and package.json
      - name: Zip the build output
        run: zip -r build.zip dist package.json package-lock.json .ebextensions

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ secrets.AWS_REGION }}

      # Upload to S3
      - name: Upload to S3
        run: aws s3 cp build.zip s3://${{ secrets.S3_BUCKET_NAME }}/

      # Deploy to Elastic Beanstalk
      - name: Deploy to AWS Elastic Beanstalk
        run: |
          aws elasticbeanstalk create-application-version \
          --application-name ${{ secrets.EB_APPLICATION_NAME }} \
          --source-bundle S3Bucket="${{ secrets.S3_BUCKET_NAME }}",S3Key="build.zip" \
          --version-label "v${{ github.run_number }}" 
          aws elasticbeanstalk update-environment --environment-name ${{ secrets.EB_ENVIRONMENT_NAME }} --version-label "v${{ github.run_number }}"
